### PR TITLE
[SDK-250] Fix endpoint in LoopmeORTB

### PR DESCRIPTION
**Pull request by ValeriiLoopMe**

### CODE REVIEW

**Comment by ValeriiLoopMe** [comment]
Fixed logic to setup correct value if it interstitial or not in "instl" key .

**Comment by hello-siok** [comment]
@ValeriiLoopMe before merging, can you elaborate the logic SDK used to decide instl = 1/0? thanks

**Comment by bzarzoza** [comment]
I'm having a hard time understanding how this change does not make all interstitial ads rewarded. @ValeriiLoopMe - can you please update this PR to show how interstitial and rewarded ads set that flag? The current description does not seem to match the behavior change, nor does the related JIRA ticket explain the change.

**Review by bzarzoza — CHANGES_REQUESTED** [review]
I'm having a hard time understanding how this change does not make all interstitial ads rewarded. @ValeriiLoopMe - can you please update this PR to show how interstitial and rewarded ads set that flag? The current description does not seem to match the behavior change, nor does the related JIRA ticket explain the change.

**Comment by ValeriiLoopMe** [comment]
I'll close this ticket because this changes doesn't need in ticket Siok wrote the rewarded and interstitial should be 1 . And we close this ticket yesterday

**Pull request closed without merging**
